name: automol-env

channels:
    - kevinmooreiii
    - auto-mech
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - numpy
    - networkx
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - kevinmooreiii::autoparse
    - auto-mech::autoread
    - auto-mech::autowrite
    - auto-mech::x2z
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental
    - conda-forge::python-igraph
