name: automol-env

channels:
    - auto-mech
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - pybind11
    - cmake
    - gcc_linux-64       # [linux]
    - gxx_linux-64       # [linux]
    - gfortran_linux-64  # [linux]
    - numpy
    - networkx
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental
    - conda-forge::nglview
    - auto-mech::autoparse
    - auto-mech::x2z
    - auto-mech::transformations
