name: autochem-env

channels:
    - pacchem
    - rdkit
    - openbabel

dependencies:
    - python
    - pybind11
    - cmake
    - gcc_linux-64       # [linux]
    - gxx_linux-64       # [linux]
    - gfortran_linux-64  # [linux]
    - numpy
    - networkx
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - rdkit::rdkit
    - openbabel::openbabel
    - pacchem::autoparse
