name: autochem-env

channels:
    - conda-forge
    - auto-mech

dependencies:
    - rdkit
    - python
    - numpy
    - scipy
    - more-itertools
    - pyyaml
    - mako
    - networkx
    - matplotlib
    - pytest
    - pytest-cov
    - ruff
    - pylint
    - ipython
    - nglview
    - py3dmol
    - qcelemental
    - cmake
    - gcc_linux-64
    - gxx_linux-64
    - gfortran_linux-64
    - pyparsing

