name: autochem-env

channels:
    - auto-mech
    - psi4
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - gfortran_linux-64  # [linux]
    - python=3.7
    - numpy
    - scipy
    - pyyaml
    - mako
    - networkx
    - matplotlib
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - psi4::psi4
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental
    - conda-forge::python-igraph
    # - auto-mech::autochem
    - auto-mech::autoio-base
    # - auto-mech::autoio-interfaces
    # - auto-mech::mechanalyzer
    - auto-mech::x2z
    # - auto-mech::mess
    # - auto-mech::projrot
    # - auto-mech::pac99
    # - auto-mech::thermp
