# cmd: conda build . -c kevinmooreiii -c rdkit -c openbabel -c conda-forge
package:
    name: automol
    version: "0.1.0"

source:
    path: .

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - networkx
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - conda-forge::nglview
        - kevinmooreiii::autoparse
        - kevinmooreiii::x2z
