# cmd: conda build . -c auto-mech -c rdkit -c openbabel -c conda-forge -c psi4
package:
    name: automol
    version: "0.5.3"

source:
    path: .

requirements:
    build:
        - python=3.7
    run:
        - gfortran_linux-64  # [linux]
        - python=3.7
        - numpy
        - scipy
        - pyyaml
        - mako
        - networkx
        - matplotlib
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        # - auto-mech::automol
        - auto-mech::autorun
        - auto-mech::autoparse
        - auto-mech::autoio
        - auto-mech::elstruct
        - auto-mech::x2z
        - psi4::psi4
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - conda-forge::python-igraph
