# cmd: conda build . -c auto-mech -c psi4 -c rdkit -c openbabel -c conda-forge
package:
    name: autochem
    version: "0.13.5"

source:
    path: .

requirements:
    build:
        - conda-forge::python
    run:
        - conda-forget::rdkit
        - conda-forge::python
        - conda-forge::numpy
        - conda-forge::scipy
        - conda-forge::more-itertools
        - conda-forge::pyyaml
        - conda-forge::mako
        - conda-forge::networkx
        - conda-forge::matplotlib
        - conda-forge::pytest
        - conda-forge::pytest-cov
        - conda-forge::ruff
        - conda-forge::ipython
        - conda-forge::nglview
        - conda-forge::py3dmol
        - conda-forge::qcelemental
        - conda-forge::cmake
        - conda-forge::gcc_linux-64
        - conda-forge::gxx_linux-64
        - conda-forge::gfortran_linux-64
        - conda-forge::pyparsing
