# cmd: conda build . -c kevinmooreiii -c auto-mech -c rdkit -c openbabel -c conda-forge
package:
    name: automol
    version: "0.5.0"

source:
    path: .

requirements:
    build:
        - python=3.7
    run:
        - python=3.7
        - numpy
        - networkx
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - auto-mech::autoparse
        - auto-mech::autoio
        - auto-mech::x2z
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
