[project]
name = "autochem"
version = "0.2026.2"
description = "Cheminformatics libraries used by the AutoMech project"
readme = "README.md"
authors = [{name = "avcopan", email = "avcopan@gmail.com"}]
dependencies = []
requires-python = ">= 3.11"

[dependency-groups]
test = ["pytest", "pytest-xdist[psutil]"]
lint = ["lefthook", "mypy", "pylint", "ruff"]
docs = ["myst-parser", "sphinx", "sphinx-autodoc-typehints", "sphinx-book-theme"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

# Hatchling configurations
[tool.hatch.build.targets.wheel]
packages = ["src/automol", "src/autochem", "src/autoreact", "src/molsym", "src/phydat"]

# Pixi configurations
[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

#   - Build
[tool.pixi.package] 
name = "autochem"

[tool.pixi.package.build] 
backend = { name = "pixi-build-python", version = "*" }

[tool.pixi.package.host-dependencies] 
hatchling = "==1.26.3"

[tool.pixi.package.run-dependencies] 
altair = ">=5.5.0"
ipython = ">=8.15"
more-itertools = ">=10.8.0"
networkx = ">=3.3"
numpy = ">=1.26"
pint = ">=0.25"
py3dmol = ">=2.5.3"
pyparsing = ">=3.2.5"
pyyaml = ">=6.0.3"
qcelemental = ">=0.29.0"
rdkit = ">=2025.9.1"
scipy = ">=1.12"
xarray = ">=2023.8"

#   - Environments
[tool.pixi.pypi-dependencies]
autochem = { path = ".", editable = true }

[tool.pixi.dependencies]
altair = ">=5.5.0"
ipython = ">=8.15"
more-itertools = ">=10.8.0"
networkx = ">=3.3"
numpy = ">=1.26"
pint = ">=0.25"
py3dmol = ">=2.5.3"
pyparsing = ">=3.2.5"
pyyaml = ">=6.0.3"
qcelemental = ">=0.29.0"
rdkit = ">=2025.9.1"
scipy = ">=1.12"
xarray = ">=2023.8"

[tool.pixi.feature.build.dependencies]
rattler-build = ">=0.47.1"
bumpver = ">=2025.1131,<2026"

[tool.pixi.environments]
test = ["test"]
lint = ["lint"]
docs = ["docs"]
build = ["build"]

#   - Tasks
[tool.pixi.feature.test.tasks]
test-automol = "pytest -n auto -v src/automol"
test-autochem = "pytest -v src/autochem"
test-autoreact = "pytest -v src/autoreact"
test = { depends-on = ["test-automol", "test-autochem", "test-autoreact"] }

[tool.pixi.feature.lint.tasks]
pre-commit = "lefthook run pre-commit --all-files"
pre-push = "lefthook run pre-push --all-files"
lint = { depends-on = ["pre-commit", "pre-push"] }
format = "ruff format"

[tool.pixi.feature.docs.tasks]
build-docs = { cmd = "make html", cwd = "docs" }

[tool.pixi.feature.build.tasks]
upload = "rattler-build upload anaconda -o Auto-Mech *.conda"
current-version = "bumpver show -n | awk -F': ' '/Current Version: / {print $2}'"

# Ruff configurations
[tool.ruff]
target-version = "py311"
exclude = ["automol", "autoreact", "molsym", "phydat", "tests", "docs"]
output-format = "concise"
fix = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",   # missing trailing comma (handled by format)
    "RUF022",   # `__all__` is not sorted
    "PLR2004",  # magic value in comparison
    "S101",     # assert statement (may want to remove this eventually)
    "TID252",   # relative import
    # resolve rule conflicts:
    "D203",     # incorrect blank line before class (uses D211 instead)
    "D213",     # multi-line summary second line (uses D212 instead)
]

[tool.bumpver]
current_version = "0.2026.2"
version_pattern = "MAJOR.YYYY.PATCH"
commit_message = "Release {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = "scripts/update_lockfile.sh"
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"src/automol/__init__.py" = [
    '__version__ = "{version}"',
]