version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install automol
                command: |
                    source activate automol-env
                    python setup.py install
            - run:
                name: Test autochem
                command: |
                    source activate automol-env
                    cd automol
                    pytest . -v --disable-pytest-warnings --cov=automol --cov=phydat --cov=transformations --pyargs automol
            - run:
                name: Test autochem format
                command: |
                    source activate automol-env
                    flake8 --exit-zero automol
                    pylint --rcfile=../.pylintrc automol
                    flake8 --exit-zero phydat
                    pylint --rcfile=../.pylintrc phydat
                    flake8 --exit-zero transformations
                    pylint --rcfile=../.pylintrc transformations
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
