version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run:
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install automol
                command: |
                    source activate autochem-env
                    python setup.py install
            - run:
                name: Test autochem
                no_output_timeout: 60m
                command: |
                    source activate autochem-env
                    cd automol
                    pytest -v --disable-pytest-warnings --cov=automol --cov=phydat --cov=autoreact --cov-report=html
                    coverage report
            - run:
                name: Test autochem format
                command: |
                    source activate autochem-env
                    flake8 --exit-zero automol
                    pylint --rcfile=.pylintrc automol 
                    flake8 --exit-zero phydat
                    pylint --rcfile=.pylintrc phydat
                    pylint --rcfile=.pylintrc autoreact
                    flake8 --exit-zero autoreact
            - store_artifacts:
                    path: automol/htmlcov
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
