version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install automol
                command: |
                    source activate automol-env
                    python setup.py install
            - run:
                name: Test automol
                command: |
                    source activate automol-env
                    cd automol
                    # pytest -v --disable-pytest-warnings --cov=automol --pyargs automol
                    flake8 --exit-zero autommol
                    pylint --rcfile=../.pylintrc automol
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian
