version: 2
jobs:
    build-debian:
        docker:
            - image: condaforge/mambaforge
        steps:
            - checkout  # checkout the code
            - run:
                name: Create conda environment
                command: |
                    mamba env create -f environment.yml
            - run:
                name: Build/install automol
                command: |
                    eval "$(conda shell.bash hook)"
                    conda activate autochem-env
                    python setup.py install
            - run:
                name: Test autochem
                no_output_timeout: 60m
                command: |
                    eval "$(conda shell.bash hook)"
                    conda activate autochem-env
                    pytest -v --disable-pytest-warnings --cov=automol --cov=phydat --cov=autoreact --cov-report=html
                    coverage report
            - run:
                name: Test autochem format
                command: |
                    eval "$(conda shell.bash hook)"
                    conda activate autochem-env
                    bash lint.sh
            - store_artifacts:
                    path: automol/htmlcov
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian  # expand out
