version: 2
jobs:
    build-debian:
        docker:
            - image: mambaorg/micromamba
        steps:
            - checkout  # checkout the code
            - run:
                name: Create conda environment
                command: |
                    micromamba create -f environment.yml -y
                    echo "********************** init micromamba shell"
                    echo 'export MAMBA_EXE="~/.local/bin/micromamba"' >> $BASH_ENV
                    echo 'export MAMBA_ROOT_PREFIX="~/micromamba"' >> $BASH_ENV
                    echo '__mamba_setup="$(~/.local/bin/micromamba shell hook --shell bash --prefix ~/micromamba 2> /dev/null)"' >> $BASH_ENV
                    echo 'eval "$__mamba_setup"' >> $BASH_ENV
            - run:
                name: Build/install automol
                command: |
                    micromamba activate autochem-env
                    python setup.py install
            - run:
                name: Test autochem
                no_output_timeout: 60m
                command: |
                    micromamba activate autochem-env
                    pytest -v --disable-pytest-warnings --cov=automol --cov=phydat --cov=autoreact --cov-report=html
                    coverage report
            - run:
                name: Test autochem format
                command: |
                    micromamba activate autochem-env
                    flake8 --exit-zero automol
                    pylint --rcfile=.pylintrc automol 
                    flake8 --exit-zero phydat
                    pylint --rcfile=.pylintrc phydat
                    flake8 --exit-zero autoreact
                    pylint --rcfile=.pylintrc autoreact
            - store_artifacts:
                    path: automol/htmlcov
workflows:
    version: 2
    build-all:
        jobs:
            - build-debian  # expand out
