# cmd: conda build . --python 2 -c conda-forge
package:
    name: x2z
    version: 0.1.1

source:
    path: .

requirements:
    build:
        - python
        - pybind11
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
    run:
        - python
        - pybind11
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - libgcc
        - pytest
        - numpy
