# cmd: conda build .
package:
    name: x2z
    version: 0.1.3

source:
    path: .

requirements:
    build:
        - python
        - pybind11
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - numpy
        - pytest
    host:
        - python
    run:
        - python
        - pybind11
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - numpy
        - pytest
