name: test

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Download environment files
        run: |
          wget https://raw.githubusercontent.com/Auto-Mech/amech-dev/main/pixi.toml
          wget https://raw.githubusercontent.com/Auto-Mech/amech-dev/main/pixi.lock

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.0

      - name: Pip install
        run: |
          pixi run pip install . --no-deps

      - name: Lint (new)
        run: |
          pixi run ./lint.sh

      - name: Lint (old)
        run: |
          pixi run pylint --rcfile=.pylintrc automol
          pixi run pylint --rcfile=.pylintrc phydat
          pixi run pylint --rcfile=.pylintrc autoreact

      - name: Test
        run: |
          pixi run pytest -v automol -v automol --ignore=automol/tests/test_convert.py
          pixi run pytest -v autoreact
