name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false

    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Download central config files
        run: |
          wget https://raw.githubusercontent.com/avcopan/amech-dev/main/pixi.toml
          wget https://raw.githubusercontent.com/avcopan/amech-dev/main/pixi.lock

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.0

      - name: Pip install
        run: |
          pixi run pip install . --no-deps

      - name: Run linter
        run: |
          pixi run pylint --rcfile=.pylintrc automol
          pixi run pylint --rcfile=.pylintrc phydat
          pixi run pylint --rcfile=.pylintrc autoreact

      - name: Run pytests
        run: |
          pixi run pytest -v --ignore=automol/tests/test_symm.py

